#pragma once

// Band-limited wavetables, generated by code (A1, CLAUDE.md §13/§20/§43).
//
// A wavetable synth's whole difficulty is aliasing. A single-cycle waveform
// read back at a high pitch contains harmonics far above Nyquist, and every
// one of them folds down into an inharmonic tone that no filter can remove
// afterwards. The usual tell of a wavetable synth written in an afternoon is
// a bright table that turns to gravel above the middle of the keyboard.
//
// The answer here is mipmapping: each single-cycle frame is stored several
// times over, each copy band-limited to a lower harmonic count, and a voice
// reads the copy whose harmonics all fit under Nyquist at the pitch it is
// playing. The copies are made by building a harmonic spectrum, zeroing what
// will not fit, and transforming back — so a level is band-limited by
// construction rather than by a filter that mostly works.
//
// Every table here is SYNTHESISED FROM A HARMONIC RECIPE at startup. Nothing
// is recorded, sampled or bundled: §20 and §43 forbid shipping content, and a
// recipe is a few lines of arithmetic rather than a megabyte of waveform.

#include "engine/core/Time.h"

#include <cstddef>
#include <string>
#include <vector>

namespace incdaw::engine {

/// One morphable set of single-cycle waveforms, band-limited per octave.
///
/// "Table position" walks across the frames; the sample between two of them
/// is a crossfade, which is what makes a wavetable a sound that MOVES rather
/// than a list of waveforms.
class Wavetable {
public:
    /// Samples in the widest-bandwidth level. 2048 gives 1024 harmonics —
    /// more than the ear has room for at any musical fundamental.
    static constexpr std::size_t frameSize = 2048;

    /// Harmonics in level 0; each level halves it.
    static constexpr int maxHarmonics = static_cast<int>(frameSize) / 2;

    /// Levels from 1024 harmonics down to 1. The last few are what keeps the
    /// top octave of the keyboard clean.
    static constexpr std::size_t levelCount = 11;


    /// Builds a table from a harmonic recipe.
    ///
    /// `amplitudeFor(harmonic, frame)` gives the amplitude of `harmonic`
    /// (1-based) in frame `frame`; anything at or below zero is silence. Each
    /// frame is normalised to unity peak afterwards, so morphing across a set
    /// does not change loudness on its own.
    Wavetable(std::string name, std::size_t frames,
              double (*amplitudeFor)(int harmonic, std::size_t frame, std::size_t frameCount));

    [[nodiscard]] const std::string& name() const noexcept { return name_; }
    [[nodiscard]] std::size_t frameCount() const noexcept { return frameCount_; }

    /// Samples in mip `level`. Every level keeps the full `frameSize`, and
    /// only its BANDWIDTH shrinks.
    ///
    /// Shortening the narrow levels would halve the memory and ruin the
    /// point: the table is read with linear interpolation, whose error grows
    /// with how close the content sits to the table's own Nyquist. A level
    /// holding 8 harmonics in 2048 points is oversampled 128 times over and
    /// interpolates to about -90 dB; the same 8 harmonics in 16 points
    /// interpolate to about -20 dB, which is the aliasing this whole class
    /// exists to avoid, reintroduced at the last step.
    [[nodiscard]] static std::size_t lengthOfLevel(std::size_t level) noexcept;

    /// Harmonics mip `level` is allowed to contain.
    [[nodiscard]] static int harmonicsOfLevel(std::size_t level) noexcept;

    /// The lowest-numbered (widest) level whose harmonics all fit below
    /// Nyquist at `frequency`. Chosen once per note, not per sample.
    [[nodiscard]] static std::size_t levelFor(double frequency, SampleRate sampleRate) noexcept;

    /// One sample. `position` morphs across the frames (0..1), `phase` is the
    /// point in the cycle (0..1), `level` picks the bandwidth. Realtime-safe:
    /// four reads and two lerps, no branches worth the name, no allocation.
    [[nodiscard]] float sample(double position, std::size_t level, double phase) const noexcept;

private:
    [[nodiscard]] const float* frameLevel(std::size_t frame, std::size_t level) const noexcept;

    std::string        name_;
    std::size_t        frameCount_ = 0;
    std::vector<float> samples_;      ///< frames × levels, each length+1 (guard)
    std::size_t        strideFrame_ = 0;
    std::size_t        offsetOfLevel_[levelCount] = {};
};

/// How many tables INCDAW ships. A constant rather than `wavetables().size()`
/// so a parameter's range can be declared without forcing every table to be
/// synthesised; the two are held together by a static assertion where the
/// catalogue is built.
inline constexpr std::size_t wavetableCount = 5;

/// The tables INCDAW ships, in catalogue order. Built once, on first call —
/// which happens off the audio thread, from the synth's prepare.
[[nodiscard]] const std::vector<Wavetable>& wavetables();

} // namespace incdaw::engine
